### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by entropical** [MickMake/GoSungrow#10]
Hey, 

I have a sungrow, and just rebuild my HomeAssistant. I have HA in Docker, so no add-on store, so I am giving this project a go.

I was a bit confused initially, because GoSungrow (i.e. the binary) did not exist. I have it now, via installing go 1.18, go build, go install.

Might be helpful to include these steps in your README.

Cheers, Brock

**Comment by MickMake** [comment]
Thanks. The goal is for people to not have to worry about building.
I'm about to push a major release along with pre-built binaries.... stay tuned.

**Comment by mmierke** [comment]
@MickMake: Hi, it would be super cool if you could provide a standalone docker image to run goSungrow as a standalone container for those of us who run HA in a docker container. Being not a docker expert it is kinda hard for me to start from the Dockerfile.

**Comment by EvoSems** [comment]
> @MickMake: Hi, it would be super cool if you could provide a standalone docker image to run goSungrow as a standalone container for those of us who run HA in a docker container. Being not a docker expert it is kinda hard for me to start from the Dockerfile.

yes please! or can you give us some instruction to build the docker file for rpi. I have been using methods as follows.

sudo docker run -d --name hass-configurator --privileged --restart=unless-stopped -v /home/evo/hass-config:/config -v /home/evo/homeassistant:/hass-config --network=host causticlab/hass-configurator-docker:latest

currently stuck on what to do on this page and it seems like the perfect project for my use case

**Comment by Paraphraser** [comment]
Short answer: yes.

How many? No idea, really. You might get some feeling for the interest in GitHub's stars/watching/forks count. The user triamazikamn <https://hub.docker.com/r/triamazikamno/amd64-addon-gosungrow>o published some rebuilt images on DockerHub and those attracted something like 3.5k downloads.

Has the project been abandoned by its author? No idea. Mick has been very quiet and nobody really knows what to make of that.

Is any development occurring? Some. As patches are contributed, I update https://gist.github.com/Paraphraser/cad3b0aa6428c58ee87bc835ac12ed37

Could we do better? Maybe. Someone with more knowledge than me needs to take the bull by the horns, fork the repository, apply the patches, and follow through the steps for Docker image generation, publishing on DockerHub and whatever glue is needed for Home Assistant to take advantage of that. Then we users need to switch over to that new binary, image or HA add-on.

Does that help?

**Comment by MarkV3082** [comment]
Yes it does, Thanks much appreciated
