### ISSUE TITLE
ERROR: unknown error 'er_missing_parameter:appkey'

### ISSUE THREAD

**Issue by hdymling** [MickMake/GoSungrow#12]
I have compiled the latest code on a Windows computer.
When trying to login Im getting the following error message "ERROR: unknown error 'er_missing_parameter:appkey'"
My configuration have an application key.
![image](https://user-images.githubusercontent.com/100768490/196027349-8ed383a8-e0eb-4c6c-ae14-fc82698aaac8.png)

When running "gosungrow api login it looks like bellow.
C:\Users\helge\Go\GoSungrow>gosungrow api login
Error: unknown error 'er_missing_parameter:appkey'
←[96;1;4mUsage:←[0m
  ←[37;1mGoSungrow←[0m api login [flags]

←[96;1;4mExamples:←[0m
←[37;3m GoSungrow api login
←[0m

Flags: Use "GoSungrow help flags" for more info.

←[96;1;4mAdditional help topics:←[0m

ERROR: unknown error 'er_missing_parameter:appkey'

**Comment by MickMake** [comment]
v3.0.0 has been released.

This fixes a lot of issues like this. Go check it out there.
