### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Azza1979** [MickMake/GoSungrow#3]
Failed to install add-on
The command '/bin/ash -o pipefail -c chmod a+x /usr/local/bin/run.sh /usr/local/bin/getUrl.sh && /usr/local/bin/getUrl.sh' returned a non-zero code: 1

**Comment by MickMake** [comment]
What device are you installing on?
Is it a Pi, PC, Mac, etc?

**Comment by Azza1979** [comment]
Rpi 4

**Comment by MickMake** [comment]
Which version of HASSIO?

I'm running
- Home Assistant Core: 2022.4.2
- Home Assistant Operating System: 7.5
- Mosquitto broker: 6.0.1

**Comment by Azza1979** [comment]
Home Assistant Core: 2022.5.1
Home Assistant Operating System: 7.6
Mosquitto broker: 6.1.1

**Comment by GazAt105** [comment]
Same issue.
Hardware: Odroid XU4 (armv7l)
Home Assistant Supervised: core-2022.6.2
OS: Linux 5.4.191-242 - Ubuntu 20.04.4 LTS
Mosquitto broker: 6.1.2

**Comment by MickMake** [comment]
Yup, definitely an issue with the way I determine which binary to pull from GitHub.
Fortunately, I have pretty much every SBC on the planet - so I'll test.

**Comment by arttwentyfourseven** [comment]
Any luck with this, mate?

**Comment by MickMake** [comment]
I've been working on v3 of GoSungrow which is a major update that adds a lot of features.

**Comment by MickMake** [comment]
v3.0.1 of the HASSIO addon has been released - https://github.com/MickMake/HomeAssistantAddons
Go check it out there.

**Comment by Azza1979** [comment]
Still getting that same error mate. 
![3D4CB38D-85F6-4F3A-9A9E-0040662AA049](https://user-images.githubusercontent.com/16231483/207967897-940864f7-78c8-4252-9c10-ce3e2db3455a.jpeg)

**Comment by knzadmin** [comment]
same problem. any news on this issue?

**Comment by Jogi284** [comment]
Hi,

I also have this issue. has someone found a solution for this?

**Comment by nithikalisamy** [comment]
Hi, I am also facing similar issue as above. Please suggest if any workarounds available. 

Did anyone found out the details on how to overcome this issue?

Core 2023.12.1
Supervisor 2023.11.6

"The command '/bin/ash -o pipefail -c chmod a+x /usr/local/bin/setup.sh && /usr/local/bin/setup.sh' returned a non-zero code: 1"

**Comment by nithikalisamy** [comment]
> v3.0.1 of the HASSIO addon has been released - https://github.com/MickMake/HomeAssistantAddons Go check it out there.

This issue is occurring again, please see if it can be addressed. Thanks.
