### ISSUE TITLE
How to access predefined / user-defined reports

### ISSUE THREAD

**Issue by thankthemaker** [MickMake/GoSungrow#47]
I use 3.0.4 and I'd like to automate sending a daily report via mail. In the web UI it's possible to use predifined reports as well as user-defined reports. How can I use these reports via GoSungrow?

I saw there's an api "getReportMsg" but I wasn't able to find out how to use it. I tried to call it like this

`./GoSungrow api get AppService.queryReportMsg`

but it returns an error message:

`Error: unknown error 'er_missing_parameter:menu_code'`

Is getting the reports supported by GoSungrow?

**Comment by thankthemaker** [comment]
BTW: I know there's also such a feature available in the UI.

**Comment by thankthemaker** [comment]
Ok, found it in the examples
`GoSungrow api get getPsReport '{"report_type":"1","date_id":"20220201","date_type":"1","ps_id":"1171348"}'`

**Comment by scraja69** [comment]
Hi,
How do you install version 3.0.4 through addons. It will not allow me. Please See below..
Can you please help?

![image](https://user-images.githubusercontent.com/42712347/232930020-563d826b-7778-4c44-af6b-93236c6c8a86.png)

**Comment by thankthemaker** [comment]
I don't use GoSungrow with HomeAssistent, instead I'm using it standanlon. Maybe someone else can answer your question.
