### ISSUE TITLE
MQTT client

### ISSUE THREAD

**Issue by doctor-eval** [MickMake/GoSungrow#52]
Hi,

I just noticed that the web app is using MQTT to communicate with iSolarCloud. Is this something you've looked into? I'm really interested in near-real-time monitoring of my solar power so I can manage demand.

cheers

<img width="943" alt="image" src="https://user-images.githubusercontent.com/57946941/233559269-bcc0711b-2b0b-4ca6-8149-10668e441d9b.png">

**Comment by bleughb** [comment]
Install Home assistant and mosquito broker and GoSungrow
