### ISSUE TITLE
Path error

### ISSUE THREAD

**Issue by ottovdv** [MickMake/GoSungrow#56]
I must be doing something wrong here, but I can't install this...
Same error on my mac as on a Linux Mint computer.

parsing go.mod:
	module declares its path as: GoSungrow
	        but was required as: github.com/MickMake/GoSungrow

**Comment by MickMake** [comment]
Have you tried downloading prebuilt binaries from the release area?

https://github.com/MickMake/GoSungrow/releases

**Comment by ottovdv** [comment]
That works, thank you. And a lot easier...
