### ISSUE TITLE
Addon will not start - fatal error

### ISSUE THREAD

**Issue by AUSPhoenix78** [MickMake/GoSungrow#6]
The addon won't start.

Error: s6-overlay-suexec: fatal: can only run as pid 1

Could we please get this fixed asap.

**Comment by joergtimm** [comment]
Same Problem

**Comment by Kawobei** [comment]
Same Where does it even install to?

**Comment by AUSPhoenix78** [comment]
have no idea, but i had another plugin that did the same thing, developer done some work and we got an update, i think this developer might be on leave or something lol i have got sick of waiting so i am using MQTT Broker and TCPtoMQTT addon along with Lovelace Power Flow card and it works a treat now, i am just going to sit back and wait patiently for this project to be updated and in the mean time use my work around, we need to remember that this is all free work so i am willing to wait.

**Comment by k158** [comment]
@AUSPhoenix78, any chance you can detail what you did?

**Comment by mikkaat** [comment]
> 

@AUSPhoenix78 I would also beinterested in how you got this workaround to function. Thanks

**Comment by MickMake** [comment]
Hi guys,
I'll be back next week, so can check it out. I suspect some update in HA has caused the issue.
It's working fine on my current version of HA that I've been upgrading over time - so something with a fresh install.

**Comment by snaven1** [comment]
I have the same problem, is this any closer to be resolved. Thanks

**Comment by Kawobei** [comment]
OFFICIAL

Can you detail how to do your work around a little more please? It might help a few of us get it going while we wait.

**Comment by Ralphy140** [comment]
I have the same issue. Someone has forked the code as described above to resolve the PID issue. but still getting errors with $home not defined. Would be great if this can be resolve in the main branch :)

**Comment by MickMake** [comment]
v3.0.1 of the HASSIO addon has been released - https://github.com/MickMake/HomeAssistantAddons

This fixes a lot of issues. Go check it out there.
