### ISSUE TITLE
When building the application on Windows Im getting error related to Undefined

### ISSUE THREAD

**Issue by hdymling** [MickMake/GoSungrow#7]
When build the code Im getting the bellow errors. Seems that the Syscall functions have changed. I know not enough to understand how to fix this.
I'm running on Windows!
# GoSungrow/lsgo
lsgo\ls-windows.go:59:18: undefined: syscall.Stat_t
lsgo\ls-windows.go:60:17: undefined: syscall.Stat
lsgo\ls-windows.go:62:43: undefined: windows.Major
lsgo\ls-windows.go:63:43: undefined: windows.Minor
# GoSungrow/mmGit
mmGit\gitFilesystem.go:248:22: undefined: syscall.ForkExec
mmGit\gitFilesystem.go:257:19: undefined: syscall.Wait4

**Comment by MickMake** [comment]
I'll be rebuilding this app next week - along with support for multiple architectures.

**Comment by MickMake** [comment]
V2.3.0 release now has support for Windows as well as a stack more architectures.

Have fun!
